export const questionDummyData = {
  questionId: 1,
  user: {
    userId: 0,
    displayName: "내 아이디는 0",
    profileImage: "이미지 url stub",
  },
  title: "질문 제목",
  body: "질문 내용",
  vote: 0,
  createdAt: "2022/12/30/14:52",
  modifiedAt: "2022/12/30/14:52",
  voteUpCheck: false,
  voteDownCheck: false,
  bookMarkCheck: true,
  tags: [],
  answers: [
    {
      answerId: 1,
      user: {
        userId: 1,
        displayName: "휴먼D",
        profileImage: "이미지 url stub",
      },
      body: "질문\n## question\n ```javascript\\nlet abc = 'hello'\\n```\n* abc\n* def\n* ",
      createdAt: "2022/12/30/14:52",
      modifiedAt: "2022/12/30/14:52",
      vote: 0,
      voteUpCheck: false,
      voteDownCheck: false,
      bookMarkCheck: true,
      comments: [
        {
          commentId: 1,
          user: {
            userId: 1,
            displayName: "휴먼D",
            profileImage: "이미지 url stub",
          },
          body: "코멘트1",
          createdAt: "2022/12/30/14:52",
          modifiedAt: "2022/12/30/14:52",
        },
        {
          commentId: 2,
          user: {
            userId: 2,
            displayName: "휴먼A",
            profileImage: "이미지 url stub",
          },
          body: "코멘트2",
          createdAt: "2022/12/30/14:52",
          modifiedAt: "2022/12/30/14:52",
        },
      ],
    },
    {
      answerId: 2,
      user: {
        userId: 2,
        displayName: "휴먼A",
        profileImage: "이미지 url stub",
      },
      body: "답변 2",
      createdAt: "2022/12/30/14:52",
      modifiedAt: "2022/12/30/14:52",
      vote: 0,
      voteUpCheck: false,
      voteDownCheck: false,
      bookMarkCheck: false,
      comments: [
        {
          commentId: 3,
          user: {
            userId: 3,
            displayName: "휴먼B",
            profileImage: "이미지 url stub",
          },
          body: "코멘트3",
          createdAt: "2022/12/30/14:52",
          modifiedAt: "2022/12/30/14:52",
        },
        {
          commentId: 4,
          user: {
            userId: 4,
            displayName: "휴먼C",
            profileImage: "이미지 url stub",
          },
          body: "코멘트4",
          createdAt: "2022/12/30/14:52",
          modifiedAt: "2022/12/30/14:52",
        },
      ],
    },
    {
      answerId: 3,
      user: {
        userId: 3,
        displayName: "휴먼B",
        profileImage: "이미지 url stub",
      },
      body: "답변 3",
      createdAt: "2022/12/30/14:52",
      modifiedAt: "2022/12/30/14:52",
      vote: 0,
      voteUpCheck: false,
      voteDownCheck: false,
      bookMarkCheck: false,
      comments: [
        {
          commentId: 5,
          user: {
            userId: 5,
            displayName: "휴먼E",
            profileImage: "이미지 url stub",
          },
          body: "코멘트5",
          createdAt: "2022/12/30/14:52",
          modifiedAt: "2022/12/30/14:52",
        },
        {
          commentId: 6,
          user: {
            userId: 1,
            displayName: "휴먼D",
            profileImage: "이미지 url stub",
          },
          body: "코멘트6",
          createdAt: "2022/12/30/14:52",
          modifiedAt: "2022/12/30/14:52",
        },
      ],
    },
  ],
};
