INSERT INTO USERS (CREATED_AT,DISPLAY_NAME,EMAIL,PASSWORD,PROFILE_IMAGE,TITLE) VALUES(CURRENT_TIMESTAMP,'유저닉네임 stub','유저 email stub','유저 password stub','이미지 url stub','유저 title stub')
INSERT INTO USERS (CREATED_AT,DISPLAY_NAME,EMAIL,PASSWORD,PROFILE_IMAGE,TITLE) VALUES(CURRENT_TIMESTAMP,'휴먼A','humanA@gmail.com',1234,'이미지 url stub','휴먼A입니다')
INSERT INTO USERS (CREATED_AT,DISPLAY_NAME,EMAIL,PASSWORD,PROFILE_IMAGE,TITLE) VALUES(CURRENT_TIMESTAMP,'휴먼B','humanB@gmail.com',1234,'이미지 url stub','휴먼B입니다')
INSERT INTO USERS (CREATED_AT,DISPLAY_NAME,EMAIL,PASSWORD,PROFILE_IMAGE,TITLE) VALUES(CURRENT_TIMESTAMP,'휴먼C','humanC@gmail.com',1234,'이미지 url stub','휴먼C입니다')

